# LSTM Classifier

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from IPython.display import Image

Let's implement classifier using LSTM. Below I prepared food paragraphs and sports paragraphs.

In [2]:
paragraph_dict_list = [
         {'paragraph': 'dishplace is located in sunnyvale downtown there is parking around the area but it can be difficult to find during peak business hours my sisters and i came to this place for dinner on a weekday they were really busy so i highly recommended making reservations unless you have the patience to wait', 'category': 'food'},
         {'paragraph': 'service can be slower during busy hours but our waiter was courteous and help gave some great entree recommendations', 'category': 'food'},
         {'paragraph': 'portions are huge both french toast and their various omelettes are really good their french toast is probably 1.5x more than other brunch places great place to visit if you are hungry and dont want to wait 1 hour for a table', 'category': 'food'},
         {'paragraph': 'we started with apps going the chicken and waffle slides and chicken nachos the sliders were amazing and the nachos were good too maybe by themselves the nachos would have scored better but after those sliders they were up against some tough competition', 'category': 'food'},
         {'paragraph': 'the biscuits and gravy was too salty two people in my group had the gravy and all thought it was too salty my hubby ordered a side of double egg and it was served on two small plates who serves eggs to one person on separate plates we commented on that when it was delivered and even the server laughed and said she doesnt know why the kitchen does that presentation of food is important and they really missed on this one', 'category': 'food'},
         {'paragraph': 'the garlic fries were a great starter (and a happy hour special) the pancakes looked and tasted great and were a fairly generous portion', 'category': 'food'},
         {'paragraph': 'our meal was excellent i had the pasta ai formaggi which was so rich i didnt dare eat it all although i certainly wanted to excellent flavors with a great texture contrast between the soft pasta and the crisp bread crumbs too much sauce for me but a wonderful dish', 'category': 'food'},
         {'paragraph': 'what i enjoy most about palo alto is so many restaurants have dog-friendly seating outside i had bookmarked italico from when they first opened about a 1.5 years ago and was jonesing for some pasta so time to finally knock that bookmark off', 'category': 'food'},
         {'paragraph': 'the drinks came out fairly quickly a good two to three minutes after the orders were taken i expected my iced tea to taste a bit more sweet but this was straight up green tea with ice in it not to complain of course but i was pleasantly surprised', 'category': 'food'},
         {'paragraph': 'despite the not so good burger the service was so slow the restaurant wasnt even half full and they took very long from the moment we got seated to the time we left it was almost 2 hours we thought that it would be quick since we ordered as soon as we sat down my coworkers did seem to enjoy their beef burgers for those who eat beef however i will not be returning it is too expensive and extremely slow service', 'category': 'food'},
    
         {'paragraph': 'the four reigning major champions simona halep caroline wozniacki angelique kerber and defending us open champion sloane stephens could make a case for being the quartet most likely to succeed especially as all but stephens has also enjoyed the no1 ranking within the last 14 months as they prepare for their gruelling new york campaigns they currently hold the top four places in the ranks', 'category': 'sports'},
         {'paragraph': 'the briton was seeded nn7 here last year before a slump in form and confidence took her down to no46 after five first-round losses but there have been signs of a turnaround including a victory over a sub-par serena williams in san jose plus wins against jelena ostapenko and victoria azarenka in montreal. konta pulled out of new haven this week with illness but will hope for good things where she first scored wins in a major before her big breakthroughs to the semis in australia and wimbledon', 'category': 'sports'},
         {'paragraph': 'stephens surged her way back from injury in stunning style to win her first major here last year—and ranked just no83 she has since proved what a big time player she is winning the miami title via four fellow major champions then reaching the final at the french open back on north american hard courts she ran to the final in montreal only just edged out by halep she has also avoided many of the big names in her quarter—except for wild card azarenka as a possible in the third round', 'category': 'sports'},
         {'paragraph': 'when it came to england chances in the world cup it would be fair to say that most fans had never been more pessimistic than they were this year after enduring years of truly dismal performances at major tournaments – culminating in the 2014 event where they failed to win any of their three group games and finished in bottom spot those results led to the resignation of manager roy hodgson', 'category': 'sports'},
         {'paragraph': 'the team that eliminated russia – croatia – also improved enormously during the tournament before it began their odds were 33/1 but they played with real flair and star players like luka modric ivan rakitic and ivan perisic showed their quality on the world stage having displayed their potential by winning all three of their group stage games croatia went on to face difficult tests like the semi-final against england', 'category': 'sports'},
         {'paragraph': 'the perseyside outfit finished in fourth place in the premier league table and without a trophy last term after having reached the champions league final before losing to real madrid', 'category': 'sports'},
         {'paragraph': 'liverpool fc will return to premier league action on saturday lunchtime when they travel to leicester city in the top flight as they look to make it four wins in a row in the league', 'category': 'sports'},
         {'paragraph': 'alisson signed for liverpool fc from as roma this summer and the brazilian goalkeeper has helped the reds to keep three clean sheets in their first three premier league games', 'category': 'sports'},
         {'paragraph': 'but the rankings during that run-in to new york hid some very different undercurrents for murray had struggled with a hip injury since the clay swing and had not played a match since losing his quarter-final at wimbledon and he would pull out of the us open just two days before the tournament began—too late however to promote nederer to the no2 seeding', 'category': 'sports'},
         {'paragraph': 'then came the oh-so-familiar djokovic-nadal no-quarter-given battle for dominance in the third set there were exhilarating rallies with both chasing to the net both retrieving what looked like winning shots nadal more than once pulled off a reverse smash and had his chance to seal the tie-break but it was djokovic serving at 10-9 who dragged one decisive error from nadal for a two-sets lead', 'category': 'sports'}
]
df = pd.DataFrame(paragraph_dict_list)
df = df[['paragraph', 'category']]

Let's take a look paragraphs where category is **food**.

In [3]:
df.head()

                                           paragraph category
0  dishplace is located in sunnyvale downtown the...     food
1  service can be slower during busy hours but ou...     food
2  portions are huge both french toast and their ...     food
3  we started with apps going the chicken and waf...     food
4  the biscuits and gravy was too salty two peopl...     food

Let's take a look paragraphs where category is **sports**.

In [4]:
df.tail()

                                            paragraph category
15  the perseyside outfit finished in fourth place...   sports
16  liverpool fc will return to premier league act...   sports
17  alisson signed for liverpool fc from as roma t...   sports
18  but the rankings during that run-in to new yor...   sports
19  then came the oh-so-familiar djokovic-nadal no...   sports

# Preprocessing
Firstly, we will take unique words from given paragraphs. we also lower all characters so we can simply NLP variance from upper and lowercases.

In [5]:
results = set()
df['paragraph'].str.lower().str.split().apply(results.update)

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
Name: paragraph, dtype: object

Each unique word's index will be numeric input to LSTM model. We will have dictionary which has key as word and value as index.

In [6]:
idx2word= dict(enumerate(results))
word2idx = {v: k for k, v in idx2word.items()}

for example, if sentence is "one week", the input to LSTM will be [15, 4]. Let's take a look word to index mapping below.

In [7]:
word2idx

{'places': 0,
 'moment': 1,
 'konta': 2,
 'serving': 3,
 'double': 4,
 'opened': 5,
 'generous': 6,
 'currently': 7,
 'happy': 8,
 'toast': 9,
 'bread': 10,
 'about': 11,
 'competition': 12,
 'then': 13,
 'winning': 14,
 'restaurant': 15,
 'the': 16,
 'began': 17,
 'including': 18,
 '1.5': 19,
 'starter': 20,
 'service': 21,
 'be': 22,
 'wild': 23,
 'keep': 24,
 'course': 25,
 'making': 26,
 'good': 27,
 'stephens': 28,
 'player': 29,
 'exhilarating': 30,
 'manager': 31,
 'wanted': 32,
 'garlic': 33,
 'results': 34,
 'action': 35,
 'so': 36,
 'gave': 37,
 'egg': 38,
 'say': 39,
 'bottom': 40,
 'expected': 41,
 'he': 42,
 'culminating': 43,
 'special)': 44,
 'waffle': 45,
 'djokovic-nadal': 46,
 'year—and': 47,
 'our': 48,
 'third': 49,
 'modric': 50,
 'dog-friendly': 51,
 'kerber': 52,
 'expensive': 53,
 'green': 54,
 'amazing': 55,
 'before': 56,
 'complain': 57,
 'tea': 58,
 'orders': 59,
 'montreal': 60,
 'pessimistic': 61,
 'enormously': 62,
 'huge': 63,
 'hip': 64,
 'even': 65,
 'halep': 66,
 'clean': 67,
 'soon': 68,
 'perseyside': 69,
 'shots': 70,
 'for': 71,
 'maybe': 72,
 'burgers': 73,
 'league': 74,
 'formaggi': 75,
 'soft': 76,
 'missed': 77,
 'nadal': 78,
 'jonesing': 79,
 'probably': 80,
 'performances': 81,
 'returning': 82,
 'a': 83,
 'eat': 84,
 'excellent': 85,
 'seating': 86,
 'to': 87,
 'busy': 88,
 'real': 89,
 'victory': 90,
 'term': 91,
 'there': 92,
 'know': 93,
 'down': 94,
 'too': 95,
 'plus': 96,
 'but': 97,
 'crumbs': 98,
 'major': 99,
 'two': 100,
 'battle': 101,
 'doesnt': 102,
 'straight': 103,
 'truly': 104,
 'four': 105,
 'flair': 106,
 'showed': 107,
 'odds': 108,
 'hid': 109,
 'courts': 110,
 'have': 111,
 'finished': 112,
 'flight': 113,
 'campaigns': 114,
 'really': 115,
 'rankings': 116,
 'succeed': 117,
 'visit': 118,
 'which': 119,
 'make': 120,
 'alto': 121,
 'she': 122,
 'five': 123,
 'error': 124,
 'top': 125,
 'however': 126,
 'thought': 127,
 'ostapenko': 128,
 'dish': 129,
 'likely': 130,
 'hungry': 131,
 'fries': 132,
 'hard': 133,
 'you': 134,
 'beef': 135,
 'illness': 136,
 'cup': 137,
 'help': 138,
 'hour': 139,
 'texture': 140,
 'restaurants': 141,
 'hubby': 142,
 'not': 143,
 'names': 144,
 'hours': 145,
 'burger': 146,
 'gruelling': 147,
 'great': 148,
 'quarter-final': 149,
 'all': 150,
 'surged': 151,
 'quickly': 152,
 'almost': 153,
 'days': 154,
 'pancakes': 155,
 'rakitic': 156,
 'things': 157,
 'haven': 158,
 'signs': 159,
 'full': 160,
 'hodgson': 161,
 'chasing': 162,
 'lunchtime': 163,
 'knock': 164,
 'place': 165,
 'apps': 166,
 'improved': 167,
 'pleasantly': 168,
 'we': 169,
 'since': 170,
 'when': 171,
 'sauce': 172,
 'extremely': 173,
 'outfit': 174,
 'proved': 175,
 'their': 176,
 'as': 177,
 'over': 178,
 'brunch': 179,
 'champions': 180,
 'will': 181,
 'year': 182,
 'where': 183,
 'area': 184,
 'fair': 185,
 'this': 186,
 'semis': 187,
 'had': 188,
 'chicken': 189,
 'was': 190,
 'sweet': 191,
 'recommended': 192,
 'omelettes': 193,
 'fourth': 194,
 'losing': 195,
 'has': 196,
 'better': 197,
 'palo': 198,
 'possible': 199,
 'biscuits': 200,
 'that': 201,
 'retrieving': 202,
 'patience': 203,
 'week': 204,
 'quick': 205,
 'breakthroughs': 206,
 '33/1': 207,
 'wimbledon': 208,
 'highly': 209,
 'eliminated': 210,
 'failed': 211,
 'back': 212,
 'both': 213,
 'wait': 214,
 'very': 215,
 'williams': 216,
 'dare': 217,
 'delivered': 218,
 'tasted': 219,
 'potential': 220,
 'find': 221,
 'played': 222,
 'meal': 223,
 'dismal': 224,
 'business': 225,
 'style': 226,
 'entree': 227,
 'york': 228,
 'bookmarked': 229,
 'chances': 230,
 'city': 231,
 'north': 232,
 'star': 233,
 'simona': 234,
 'looked': 235,
 'out': 236,
 'once': 237,
 'want': 238,
 'also': 239,
 'of': 240,
 'roma': 241,
 'dishplace': 242,
 'oh-so-familiar': 243,
 'got': 244,
 'waiter': 245,
 'dominance': 246,
 'said': 247,
 'seeding': 248,
 'just': 249,
 'long': 250,
 'net': 251,
 'ran': 252,
 'us': 253,
 'ago': 254,
 'contrast': 255,
 'card': 256,
 'tests': 257,
 'sat': 258,
 'croatia': 259,
 'ranked': 260,
 'some': 261,
 'two-sets': 262,
 'enjoyed': 263,
 'than': 264,
 'ranks': 265,
 'they': 266,
 'round': 267,
 'after': 268,
 'seeded': 269,
 'served': 270,
 'dinner': 271,
 'outside': 272,
 'open': 273,
 'liverpool': 274,
 'me': 275,
 'why': 276,
 'coworkers': 277,
 'weekday': 278,
 'who': 279,
 'bit': 280,
 'san': 281,
 'on': 282,
 'is': 283,
 'within': 284,
 'three': 285,
 'serves': 286,
 'reigning': 287,
 'avoided': 288,
 'parking': 289,
 'enduring': 290,
 'no2': 291,
 'stage': 292,
 'big': 293,
 'win': 294,
 'quarter—except': 295,
 'wasnt': 296,
 'spot': 297,
 'dragged': 298,
 'players': 299,
 'run-in': 300,
 'hope': 301,
 'late': 302,
 'row': 303,
 'taste': 304,
 'bookmark': 305,
 'nn7': 306,
 'azarenka': 307,
 'crisp': 308,
 'tournament': 309,
 'more': 310,
 'reservations': 311,
 'title': 312,
 'peak': 313,
 'slow': 314,
 'rich': 315,
 'look': 316,
 'up': 317,
 'ice': 318,
 'without': 319,
 'surprised': 320,
 'at': 321,
 'signed': 322,
 'laughed': 323,
 'took': 324,
 'tournaments': 325,
 'having': 326,
 'no46': 327,
 'angelique': 328,
 'final': 329,
 'goalkeeper': 330,
 'salty': 331,
 '10-9': 332,
 '2': 333,
 'case': 334,
 'could': 335,
 'separate': 336,
 'never': 337,
 'brazilian': 338,
 'confidence': 339,
 'saturday': 340,
 'scored': 341,
 'flavors': 342,
 'french': 343,
 'premier': 344,
 'resignation': 345,
 'table': 346,
 'can': 347,
 'certainly': 348,
 'chance': 349,
 'trophy': 350,
 'different': 351,
 'perisic': 352,
 'promote': 353,
 'injury': 354,
 'people': 355,
 'serena': 356,
 'it': 357,
 'located': 358,
 'plates': 359,
 'italico': 360,
 'months': 361,
 'one': 362,
 'new': 363,
 'around': 364,
 'summer': 365,
 'jelena': 366,
 'displayed': 367,
 'event': 368,
 'australia': 369,
 'fairly': 370,
 'seated': 371,
 'themselves': 372,
 'if': 373,
 'and': 374,
 'important': 375,
 'started': 376,
 'dont': 377,
 'rallies': 378,
 'person': 379,
 'last': 380,
 'semi-final': 381,
 'set': 382,
 'finally': 383,
 'kitchen': 384,
 'been': 385,
 'murray': 386,
 'against': 387,
 'nederer': 388,
 'enjoy': 389,
 'with': 390,
 'eggs': 391,
 'caroline': 392,
 'being': 393,
 'from': 394,
 'those': 395,
 'group': 396,
 'much': 397,
 'defending': 398,
 'first-round': 399,
 'decisive': 400,
 'travel': 401,
 '(and': 402,
 'off': 403,
 'server': 404,
 'miami': 405,
 'clay': 406,
 'djokovic': 407,
 'especially': 408,
 'were': 409,
 'ordered': 410,
 'half': 411,
 'lead': 412,
 'team': 413,
 'russia': 414,
 'taken': 415,
 'sheets': 416,
 'smash': 417,
 'downtown': 418,
 'despite': 419,
 'leicester': 420,
 'courteous': 421,
 'led': 422,
 'champion': 423,
 'reached': 424,
 'although': 425,
 'reds': 426,
 'tie-break': 427,
 'american': 428,
 'jose': 429,
 '1.5x': 430,
 'does': 431,
 'seal': 432,
 'pasta': 433,
 'didnt': 434,
 'came': 435,
 'briton': 436,
 'only': 437,
 'sub-par': 438,
 'what': 439,
 'first': 440,
 'via': 441,
 'like': 442,
 'i': 443,
 'ai': 444,
 'between': 445,
 'small': 446,
 'portion': 447,
 'slides': 448,
 'way': 449,
 'england': 450,
 '2014': 451,
 'his': 452,
 'slower': 453,
 'would': 454,
 'going': 455,
 'return': 456,
 'luka': 457,
 'gravy': 458,
 'match': 459,
 '14': 460,
 'iced': 461,
 'turnaround': 462,
 'reverse': 463,
 'pulled': 464,
 'montreal.': 465,
 'any': 466,
 'alisson': 467,
 'sisters': 468,
 'wins': 469,
 'wonderful': 470,
 'sloane': 471,
 'drinks': 472,
 'my': 473,
 'left': 474,
 'fellow': 475,
 'years': 476,
 'victoria': 477,
 'undercurrents': 478,
 'food': 479,
 'seem': 480,
 'slump': 481,
 'time': 482,
 'presentation': 483,
 'prepare': 484,
 'here': 485,
 'side': 486,
 'sunnyvale': 487,
 'in': 488,
 'did': 489,
 'went': 490,
 'tough': 491,
 'ranking': 492,
 'no-quarter-given': 493,
 'madrid': 494,
 'struggled': 495,
 'wozniacki': 496,
 'pull': 497,
 'roy': 498,
 'her': 499,
 'hold': 500,
 'other': 501,
 'form': 502,
 'stunning': 503,
 'recommendations': 504,
 'portions': 505,
 '–': 506,
 'no1': 507,
 'nachos': 508,
 'world': 509,
 'began—too': 510,
 'difficult': 511,
 'games': 512,
 'swing': 513,
 'during': 514,
 'face': 515,
 'various': 516,
 'are': 517,
 '1': 518,
 'helped': 519,
 'sliders': 520,
 'unless': 521,
 'ivan': 522,
 'by': 523,
 'commented': 524,
 'no83': 525,
 'many': 526,
 'minutes': 527,
 'fc': 528,
 'quartet': 529,
 'fans': 530,
 'most': 531,
 'quality': 532,
 'reaching': 533,
 'losses': 534,
 'edged': 535}

Since now we have word to index dictionary, let's encode paragraphs to index.

In [8]:
def encode_paragraph(paragraph):
    words = paragraph.split(" ")
    encoded = []
    for word in words:
        encoded.append([word2idx[word]])
    
    return encoded

df["enc_paragraph"] = df.paragraph.apply(encode_paragraph)

We also need to encode category to numeric value in order to fit in deep learning model. Here we encoding category as one hot encoding.

In [9]:
def encode_category(category):
    if category == "food":
        return [1,0]
    else:
        return [0,1]
    
df["enc_category"] = df.category.apply(encode_category)

In order to run dynamic RNN, we need to know the word count for each paragraph.

In [10]:
def word_cnt(paragraph):
    return len(paragraph.split(" "))

df["seq_length"] = df.paragraph.apply(word_cnt)

Dynamic RNN needs two parameters, first is input sequence and the second is the length of original input.  
By design of RNN, input sequence must be same to all inputs, therefore shorter input will have additional paddings.  
The purpose of second parameter "the length of original input" is to help RNN to skip additional paddings when it returns hidden state.

In [11]:
max_word_cnt = 0
for row in df['paragraph']:
    if len(row.split(" ")) > max_word_cnt:
        max_word_cnt = len(row.split(" "))

print (max_word_cnt)

91

In [12]:
def sequence_padding(enc_paragraph):
    seq_length = len(enc_paragraph)
    for i in range(seq_length,max_word_cnt):
        enc_paragraph.append([-1])
    
    return enc_paragraph

df["enc_paragraph"] = df.enc_paragraph.apply(sequence_padding)

let's take a look a sample below, where we can find additional padding in the encoded paragraph.

In [13]:
print(df["enc_paragraph"][0])

[[242], [283], [358], [488], [487], [418], [92], [283], [289], [364], [16], [184], [97], [357], [347], [22], [511], [87], [221], [514], [313], [225], [145], [473], [468], [374], [443], [435], [87], [186], [165], [71], [271], [282], [83], [278], [266], [409], [115], [88], [36], [443], [209], [192], [26], [311], [521], [134], [111], [16], [203], [87], [214], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1]]

Now, we have all numeric values for our LSTM category classifier.

In [14]:
df.head(20)

,paragraph,category,enc_paragraph,enc_category,seq_length
0,dishplace is located in sunnyvale downtown the...,food,"[[242], [283], [358], [488], [487], [418], [92...","[1, 0]",53
1,service can be slower during busy hours but ou...,food,"[[21], [347], [22], [453], [514], [88], [145],...","[1, 0]",19
2,portions are huge both french toast and their ...,food,"[[505], [517], [63], [213], [343], [9], [374],...","[1, 0]",42
3,we started with apps going the chicken and waf...,food,"[[169], [376], [390], [166], [455], [16], [189...","[1, 0]",43
4,the biscuits and gravy was too salty two peopl...,food,"[[16], [200], [374], [458], [190], [95], [331]...","[1, 0]",82
5,the garlic fries were a great starter (and a h...,food,"[[16], [33], [132], [409], [83], [148], [20], ...","[1, 0]",24
6,our meal was excellent i had the pasta ai form...,food,"[[48], [223], [190], [85], [443], [188], [16],...","[1, 0]",50
7,what i enjoy most about palo alto is so many r...,food,"[[439], [443], [389], [531], [11], [198], [121...","[1, 0]",43
8,the drinks came out fairly quickly a good two ...,food,"[[16], [472], [435], [236], [370], [152], [83]...","[1, 0]",49
9,despite the not so good burger the service was...,food,"[[419], [16], [143], [36], [27], [146], [16], ...","[1, 0]",82
10,the four reigning major champions simona halep...,sports,"[[16], [105], [287], [99], [180], [234], [66],...","[0, 1]",65
11,the briton was seeded nn7 here last year befor...,sports,"[[16], [436], [190], [269], [306], [485], [380...","[0, 1]",88
12,stephens surged her way back from injury in st...,sports,"[[28], [151], [499], [449], [212], [394], [354...","[0, 1]",91
13,when it came to england chances in the world c...,sports,"[[171], [357], [435], [87], [450], [230], [488...","[0, 1]",71
14,the team that eliminated russia – croatia – al...,sports,"[[16], [413], [201], [210], [414], [506], [259...","[0, 1]",70
15,the perseyside outfit finished in fourth place...,sports,"[[16], [69], [174], [112], [488], [194], [165]...","[0, 1]",30
16,liverpool fc will return to premier league act...,sports,"[[274], [528], [181], [456], [87], [344], [74]...","[0, 1]",35
17,alisson signed for liverpool fc from as roma t...,sports,"[[467], [322], [71], [274], [528], [394], [177...","[0, 1]",30
18,but the rankings during that run-in to new yor...,sports,"[[97], [16], [116], [514], [201], [300], [87],...","[0, 1]",63
19,then came the oh-so-familiar djokovic-nadal no...,sports,"[[13], [435], [16], [243], [46], [493], [101],...","[0, 1]",65

In order to train our LSTM model, we will use enc_paragraph, enc_category, and seq_length.  
enc_paragraph: input   
enc_category: target  
seq_length: second parameter of Dynamic RNN

In [15]:
enc_paragraph = np.array(df.enc_paragraph.tolist())
enc_category = np.array(df.enc_category.tolist())
seq_length = np.array(df.seq_length.tolist())

In [16]:
train_X = enc_paragraph

In [17]:
train_Y = enc_category

We can see our train data has 20 examples with 91 input sequence.

In [18]:
train_X.shape

(20, 91, 1)

We can see our target has 20 examples with 2 dimension. the two dimension is for one hot encoding of category.  
[1, 0] : food  
[0, 1] : sports

In [19]:
train_Y.shape

(20, 2)

# Build TF Model

we will build TF model below model architecture.  
embedding is to generate dense embedding vector which provides word similarity info to the model.  
embedding to lstm layer is to generate contextual vector where sentence meaning represented by number.  
dense layers is to classify contextual vector to categories.

In [20]:
Image(url= "https://raw.githubusercontent.com/minsuk-heo/deeplearning/master/img/lstm_model_overview.png", width=500, height=250)

In [21]:
tf.reset_default_graph()
tf.set_random_seed(777)

# hyperparameters
learning_rate = 0.001
n_epochs = 300

# define input
X = tf.placeholder(tf.float32, [None,max_word_cnt,1])
# define output
y = tf.placeholder(tf.int32, [None, 2])

# word embedding layer
embedding = tf.layers.dense(X, 5)
# LSTM cell
cell = tf.nn.rnn_cell.LSTMCell(num_units=64)
# get output and state (we only use state in this example)
output, state = tf.nn.dynamic_rnn(cell, embedding, dtype=tf.float32, sequence_length=seq_length)
# state is contextual vector which is input to MLP classifier (dense layer) below
dense_layer = tf.layers.dense(state.h, 32)
# logit has two nodes for cross entropy with one hot encoding target
logits = tf.layers.dense(dense_layer, 2)
# loss function
cross_entropy = tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=logits)
loss = tf.reduce_mean(cross_entropy)
# Adam Optimizor
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)

# Model Summary
here is tf model summary.  
[generate contextual vector]
input is index of words, the fixed sequence length is 91.  
then input goes embedding layer and the output of embedding has 5 dimension vector.  
LSTM cell outputs 64 dimension vector.  
[classify contextual vector to category]
first dense layer gets 64 dimension vector and output 32 dimension vector.  
second dense layer gets 32 dimension vector and outputs 2 dimension vector.  
2 dimension vector goes softmax.

In [22]:
print(X)
print(embedding)
print(state)
print(dense_layer)
print(logits)

Tensor("Placeholder:0", shape=(?, 91, 1), dtype=float32)
Tensor("dense/BiasAdd:0", shape=(?, 91, 5), dtype=float32)
LSTMStateTuple(c=<tf.Tensor 'rnn/while/Exit_3:0' shape=(?, 64) dtype=float32>, h=<tf.Tensor 'rnn/while/Exit_4:0' shape=(?, 64) dtype=float32>)
Tensor("dense_1/BiasAdd:0", shape=(?, 32), dtype=float32)
Tensor("dense_2/BiasAdd:0", shape=(?, 2), dtype=float32)

# Train

In [23]:
# initialize the variables
init = tf.global_variables_initializer()

# Start training
with tf.Session() as sess:
    # Run the initializer
    sess.run(init)
    for epoch in range(1, n_epochs+1):
        sess.run(optimizer, feed_dict={X: train_X, y: train_Y})
        train_loss = sess.run(loss, feed_dict={X: train_X, y: train_Y})

        if epoch == 1 or epoch % 50 == 0:
            preds = tf.nn.softmax(logits)  # Apply softmax to logits
            correct_prediction = tf.equal(tf.argmax(preds, 1), tf.argmax(y, 1))
            # Calculate accuracy
            accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
            cur_acc = accuracy.eval({X: train_X, y: train_Y})
            print("epoch: "+ str(epoch)+", loss: "+str(train_loss)+", accuracy: "+str(cur_acc))

epoch: 1, loss: 0.6670772, accuracy: 0.6
epoch: 50, loss: 0.41899902, accuracy: 0.85
epoch: 100, loss: 0.1634014, accuracy: 0.95
epoch: 150, loss: 0.01540491, accuracy: 1.0
epoch: 200, loss: 0.0038772952, accuracy: 1.0
epoch: 250, loss: 0.0017035162, accuracy: 1.0
epoch: 300, loss: 0.0010282218, accuracy: 1.0

Our LSTM model successfully classified all paragraphs to its category. Congratulation!